"""Explicit SQL migrations; spatial DDL is never autogenerated."""
import asyncio

from alembic import context
from sqlalchemy.ext.asyncio import create_async_engine

from pec.config import Settings


def run(connection):
    context.configure(connection=connection, transaction_per_migration=True)
    with context.begin_transaction():
        context.run_migrations()


async def online():
    engine = create_async_engine(Settings.from_env().database_url, pool_pre_ping=True)
    async with engine.connect() as connection:
        await connection.run_sync(run)
    await engine.dispose()


if context.is_offline_mode():
    context.configure(url="postgresql://", literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()
else:
    asyncio.run(online())

