CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE sources (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 key TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL,
 source_type TEXT NOT NULL,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE source_roles (
 source_id BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
 role TEXT NOT NULL CHECK (role IN ('DISCOVERY','PLANNING','WATCH_SIGNAL','CONFIRMATION','CORROBORATION','CONDITION','ACCESS','SAFETY')),
 PRIMARY KEY(source_id, role)
);
CREATE TABLE source_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_id BIGINT NOT NULL REFERENCES sources(id),
 cycle_key TEXT NOT NULL,
 attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
 started_at TIMESTAMPTZ NOT NULL,
 completed_at TIMESTAMPTZ NOT NULL,
 status TEXT NOT NULL CHECK (status IN ('success','failure','parser_failure')),
 http_status INTEGER CHECK (http_status BETWEEN 100 AND 599),
 records_received INTEGER NOT NULL DEFAULT 0 CHECK (records_received >= 0),
 records_accepted INTEGER NOT NULL DEFAULT 0 CHECK (records_accepted >= 0),
 records_rejected INTEGER NOT NULL DEFAULT 0 CHECK (records_rejected >= 0),
 provider_updated_at TIMESTAMPTZ,
 latency_ms INTEGER NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
 error_code TEXT,
 CHECK (completed_at >= started_at),
 CHECK (records_accepted + records_rejected <= records_received),
 UNIQUE(source_id, cycle_key, attempt_number)
);
CREATE INDEX ix_source_runs_latest ON source_runs(source_id, completed_at DESC, id DESC);
CREATE INDEX ix_source_runs_retention ON source_runs(completed_at);
CREATE TABLE source_backoff (
 source_id BIGINT PRIMARY KEY REFERENCES sources(id),
 next_allowed_at TIMESTAMPTZ NOT NULL,
 consecutive_failures INTEGER NOT NULL CHECK (consecutive_failures >= 0)
);
CREATE TABLE raw_observations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_id BIGINT NOT NULL REFERENCES sources(id),
 source_run_id BIGINT REFERENCES source_runs(id),
 external_id TEXT,
 observed_at TIMESTAMPTZ,
 fetched_at TIMESTAMPTZ NOT NULL,
 exact_geometry geometry(Point,4326),
 raw_payload JSONB,
 parser_version TEXT NOT NULL,
 UNIQUE(source_id, external_id)
);
CREATE INDEX ix_raw_run ON raw_observations(source_run_id);
CREATE INDEX ix_raw_retention ON raw_observations(fetched_at);
CREATE INDEX ix_raw_observed ON raw_observations(observed_at);
CREATE TABLE normalized_observations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 raw_observation_id BIGINT NOT NULL REFERENCES raw_observations(id),
 subject_type TEXT NOT NULL CHECK (subject_type IN ('species','behavior')),
 subject_key TEXT NOT NULL,
 observed_at TIMESTAMPTZ NOT NULL,
 analysis_geometry geometry(Point,4326),
 public_geometry geometry(Point,4326),
 reported_count INTEGER CHECK (reported_count >= 0),
 sensitive BOOLEAN NOT NULL DEFAULT FALSE,
 precision_class TEXT NOT NULL CHECK (precision_class IN ('exact','curated_public_site','region','withheld')),
 valid_until TIMESTAMPTZ NOT NULL,
 CHECK (valid_until >= observed_at),
 CHECK (NOT sensitive OR precision_class != 'exact'),
 UNIQUE(raw_observation_id, subject_type, subject_key)
);
CREATE INDEX ix_normalized_validity ON normalized_observations(valid_until);
CREATE INDEX ix_normalized_subject_time ON normalized_observations(subject_key, observed_at);
CREATE INDEX ix_normalized_analysis ON normalized_observations USING gist(analysis_geometry);
CREATE TABLE locations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 key TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL,
 geometry geometry(Geometry,4326),
 public_geometry geometry(Geometry,4326),
 location_type TEXT NOT NULL,
 sensitivity TEXT NOT NULL CHECK (sensitivity IN ('public','restricted')),
 timezone TEXT NOT NULL DEFAULT 'America/Los_Angeles'
);
CREATE TABLE phenomenon_locations (
 definition_key TEXT NOT NULL,
 location_id BIGINT NOT NULL REFERENCES locations(id),
 role TEXT NOT NULL CHECK (role IN ('primary','public_viewpoint')),
 PRIMARY KEY(definition_key, location_id)
);
CREATE INDEX ix_phenomenon_locations_location ON phenomenon_locations(location_id);
CREATE TABLE route_baselines (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 origin_key TEXT NOT NULL,
 location_id BIGINT NOT NULL REFERENCES locations(id),
 routing_profile TEXT NOT NULL,
 distance_miles DOUBLE PRECISION NOT NULL CHECK (distance_miles >= 0 AND distance_miles < 'Infinity'),
 drive_minutes DOUBLE PRECISION NOT NULL CHECK (drive_minutes >= 0 AND drive_minutes < 'Infinity'),
 provider TEXT NOT NULL,
 calculated_at TIMESTAMPTZ NOT NULL,
 invalidated_at TIMESTAMPTZ,
 UNIQUE(origin_key, location_id, routing_profile)
);
CREATE INDEX ix_route_location ON route_baselines(location_id);
CREATE TABLE assessment_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 generated_at TIMESTAMPTZ NOT NULL,
 data_as_of TIMESTAMPTZ NOT NULL,
 valid_until TIMESTAMPTZ NOT NULL,
 scope TEXT NOT NULL CHECK (scope = 'tule_elk_rut'),
 state TEXT NOT NULL CHECK (state IN ('complete','incomplete','degraded')),
 CHECK (valid_until >= data_as_of)
);
CREATE INDEX ix_assessment_latest ON assessment_runs(generated_at DESC, id DESC);
CREATE TABLE opportunities (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 occurrence_key TEXT NOT NULL UNIQUE,
 phenomenon_key TEXT NOT NULL,
 location_id BIGINT NOT NULL REFERENCES locations(id),
 assessment_run_id BIGINT NOT NULL REFERENCES assessment_runs(id),
 starts_at TIMESTAMPTZ NOT NULL,
 ends_at TIMESTAMPTZ NOT NULL CHECK (ends_at >= starts_at),
 category TEXT NOT NULL CHECK (category IN ('mammals','birds')),
 presentation TEXT NOT NULL CHECK (presentation IN ('cant_miss','watching','planner','held','bird_spectacle','bird_encounter')),
 eligibility BOOLEAN NOT NULL,
 significance INTEGER NOT NULL CHECK (significance BETWEEN 0 AND 100),
 confidence INTEGER NOT NULL CHECK (confidence BETWEEN 0 AND 100),
 urgency INTEGER NOT NULL CHECK (urgency BETWEEN 0 AND 100),
 evidence_state TEXT NOT NULL,
 access_state TEXT NOT NULL,
 safety_state TEXT NOT NULL CHECK (safety_state IN ('safe','caution','unsafe','unknown')),
 condition_state TEXT NOT NULL,
 drive_minutes DOUBLE PRECISION CHECK (drive_minutes >= 0 AND drive_minutes < 'Infinity'),
 drive_basis TEXT NOT NULL,
 reason TEXT NOT NULL,
 awaiting TEXT NOT NULL,
 definition_key TEXT NOT NULL,
 definition_version TEXT NOT NULL,
 definition_hash TEXT NOT NULL CHECK (length(definition_hash) = 64),
 engine_version TEXT NOT NULL,
 data_as_of TIMESTAMPTZ NOT NULL,
 valid_until TIMESTAMPTZ NOT NULL,
 product JSONB NOT NULL,
 CHECK (NOT eligibility OR presentation = 'cant_miss')
);
CREATE INDEX ix_opportunity_assessment ON opportunities(assessment_run_id);
CREATE INDEX ix_opportunity_location ON opportunities(location_id);
CREATE INDEX ix_opportunity_phenomenon ON opportunities(phenomenon_key);
CREATE INDEX ix_opportunity_active ON opportunities(presentation, ends_at);
CREATE TABLE opportunity_revisions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 opportunity_id BIGINT NOT NULL REFERENCES opportunities(id),
 recorded_at TIMESTAMPTZ NOT NULL,
 presentation TEXT NOT NULL,
 eligibility BOOLEAN NOT NULL,
 significance INTEGER NOT NULL,
 confidence INTEGER NOT NULL,
 urgency INTEGER NOT NULL,
 evidence_state TEXT NOT NULL,
 access_state TEXT NOT NULL,
 safety_state TEXT NOT NULL,
 condition_state TEXT NOT NULL,
 reason TEXT NOT NULL,
 definition_version TEXT NOT NULL,
 definition_hash TEXT NOT NULL,
 engine_version TEXT NOT NULL
);
CREATE INDEX ix_revision_opportunity ON opportunity_revisions(opportunity_id, recorded_at);
CREATE TABLE opportunity_observation_evidence (
 opportunity_id BIGINT NOT NULL REFERENCES opportunities(id),
 normalized_observation_id BIGINT NOT NULL REFERENCES normalized_observations(id),
 disposition TEXT NOT NULL CHECK (disposition IN ('SUPPORTING','CONTRADICTORY','NEUTRAL')),
 PRIMARY KEY(opportunity_id, normalized_observation_id)
);
CREATE INDEX ix_evidence_observation ON opportunity_observation_evidence(normalized_observation_id);
CREATE TABLE opportunity_context_evidence (
 opportunity_id BIGINT NOT NULL REFERENCES opportunities(id),
 source_run_id BIGINT NOT NULL REFERENCES source_runs(id),
 disposition TEXT NOT NULL CHECK (disposition IN ('SUPPORTING','CONTRADICTORY','NEUTRAL')),
 PRIMARY KEY(opportunity_id, source_run_id)
);
CREATE INDEX ix_evidence_context ON opportunity_context_evidence(source_run_id);
CREATE VIEW source_health_current AS
 SELECT s.key, s.enabled, last_run.started_at AS last_attempt_at, last_run.status,
 last_run.error_code, last_success.completed_at AS last_success_at,
 last_success.provider_updated_at
 FROM sources s
 LEFT JOIN LATERAL (SELECT * FROM source_runs r WHERE r.source_id=s.id ORDER BY completed_at DESC, id DESC LIMIT 1) last_run ON TRUE
 LEFT JOIN LATERAL (SELECT * FROM source_runs r WHERE r.source_id=s.id AND status='success' ORDER BY completed_at DESC, id DESC LIMIT 1) last_success ON TRUE;
