CREATE TABLE observation_report_groups (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 origin_namespace TEXT NOT NULL CHECK(length(origin_namespace)>0),
 origin_external_id TEXT NOT NULL CHECK(length(origin_external_id)>0),
 created_at TIMESTAMPTZ NOT NULL,
 UNIQUE(origin_namespace,origin_external_id)
);
CREATE TABLE observation_report_group_members (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 report_group_id BIGINT NOT NULL REFERENCES observation_report_groups(id),
 normalized_observation_id BIGINT NOT NULL REFERENCES normalized_observations(id),
 link_basis TEXT NOT NULL CHECK(link_basis IN ('provider_identity','explicit_origin_id')),
 created_at TIMESTAMPTZ NOT NULL,
 superseded_at TIMESTAMPTZ,
 UNIQUE(id,normalized_observation_id,report_group_id),
 CHECK(superseded_at IS NULL OR superseded_at>=created_at)
);
CREATE UNIQUE INDEX ux_report_current ON observation_report_group_members(normalized_observation_id) WHERE superseded_at IS NULL;
CREATE INDEX ix_report_group_current ON observation_report_group_members(report_group_id) WHERE superseded_at IS NULL;
ALTER TABLE normalized_observations ADD COLUMN coordinate_uncertainty_meters DOUBLE PRECISION CHECK(coordinate_uncertainty_meters>=0 AND coordinate_uncertainty_meters<'Infinity'::float8);
ALTER TABLE normalized_observations ADD COLUMN spatial_precision TEXT NOT NULL DEFAULT 'unknown' CHECK(spatial_precision IN ('point','area','unknown'));
ALTER TABLE normalized_observations ADD COLUMN credible BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE normalized_observation_behaviors (
 normalized_observation_id BIGINT NOT NULL REFERENCES normalized_observations(id),
 behavior_code TEXT NOT NULL CHECK(behavior_code IN ('presence','feeding','fishing','courtship','rut','mating','pupping','aggregation','migration','roosting','sow_with_cubs','lunge_feeding','breaching')),
 created_at TIMESTAMPTZ NOT NULL,
 PRIMARY KEY(normalized_observation_id,behavior_code)
);
CREATE INDEX ix_behavior_code ON normalized_observation_behaviors(behavior_code,normalized_observation_id);
-- Backfill identity, not precision. Legacy points with unknown accuracy remain unknown for M2.
INSERT INTO observation_report_groups(origin_namespace,origin_external_id,created_at)
 SELECT DISTINCT s.key,COALESCE(r.external_id,'legacy-raw-'||r.id),r.fetched_at
 FROM raw_observations r JOIN sources s ON s.id=r.source_id;
INSERT INTO observation_report_group_members(report_group_id,normalized_observation_id,link_basis,created_at,superseded_at)
 SELECT g.id,n.id,'provider_identity',r.fetched_at,GREATEST(n.superseded_at,r.fetched_at)
 FROM normalized_observations n JOIN raw_observations r ON r.id=n.raw_observation_id
 JOIN sources s ON s.id=r.source_id JOIN observation_report_groups g
 ON g.origin_namespace=s.key AND g.origin_external_id=COALESCE(r.external_id,'legacy-raw-'||r.id);
-- PostgreSQL GREATEST ignores NULL; restore NULL for current assertions explicitly.
UPDATE observation_report_group_members m SET superseded_at=NULL FROM normalized_observations n
 WHERE n.id=m.normalized_observation_id AND n.superseded_at IS NULL;
INSERT INTO normalized_observation_behaviors
 SELECT id,'presence',observed_at FROM normalized_observations WHERE subject_type='species';
INSERT INTO normalized_observation_behaviors
 SELECT id,behavior,observed_at FROM normalized_observations
 WHERE behavior IN ('feeding','fishing','courtship','rut','mating','pupping','aggregation','migration','roosting','sow_with_cubs','lunge_feeding','breaching');
CREATE TABLE pattern_episodes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 episode_key TEXT NOT NULL UNIQUE,
 phenomenon_key TEXT NOT NULL,
 subject_key TEXT NOT NULL,
 compatibility_key TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('developing','qualified','ended')),
 started_at TIMESTAMPTZ NOT NULL,
 last_supported_at TIMESTAMPTZ NOT NULL,
 ended_at TIMESTAMPTZ,
 public_location_id BIGINT REFERENCES locations(id),
 contains_sensitive_evidence BOOLEAN NOT NULL,
 policy_version TEXT NOT NULL,
 policy_hash TEXT NOT NULL CHECK(length(policy_hash)=64),
 continuation_gap_seconds INTEGER NOT NULL CHECK(continuation_gap_seconds>0),
 parent_episode_id BIGINT REFERENCES pattern_episodes(id),
 merged_into_episode_id BIGINT REFERENCES pattern_episodes(id),
 created_at TIMESTAMPTZ NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL,
 CHECK((status='ended')=(ended_at IS NOT NULL)),
 CHECK(id IS DISTINCT FROM parent_episode_id AND id IS DISTINCT FROM merged_into_episode_id)
);
CREATE INDEX ix_episode_active ON pattern_episodes(phenomenon_key,last_supported_at) WHERE status<>'ended';
CREATE TABLE observation_clusters (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 assessment_run_id BIGINT NOT NULL REFERENCES assessment_runs(id),
 phenomenon_key TEXT NOT NULL,
 cluster_key TEXT NOT NULL CHECK(length(cluster_key)=64),
 pattern_episode_id BIGINT REFERENCES pattern_episodes(id),
 policy_version TEXT NOT NULL,
 policy_hash TEXT NOT NULL CHECK(length(policy_hash)=64),
 engine_version TEXT NOT NULL,
 clustering_crs INTEGER NOT NULL,
 calculated_at TIMESTAMPTZ NOT NULL,
 centroid_internal GEOMETRY(Point,4326) NOT NULL,
 bounding_center_internal GEOMETRY(Point,4326) NOT NULL,
 radius_meters DOUBLE PRECISION NOT NULL CHECK(radius_meters>=0 AND radius_meters<'Infinity'::float8),
 provider_record_count INTEGER NOT NULL CHECK(provider_record_count>0),
 observation_count INTEGER NOT NULL CHECK(observation_count>0),
 independent_report_count INTEGER NOT NULL CHECK(independent_report_count>0),
 independent_source_count INTEGER NOT NULL CHECK(independent_source_count>0),
 max_single_report_count INTEGER CHECK(max_single_report_count>=0),
 window_start TIMESTAMPTZ NOT NULL,
 window_end TIMESTAMPTZ NOT NULL,
 first_observed_at TIMESTAMPTZ NOT NULL,
 last_observed_at TIMESTAMPTZ NOT NULL,
 contains_sensitive_evidence BOOLEAN NOT NULL,
 qualification_state TEXT NOT NULL CHECK(qualification_state IN ('developing','qualified')),
 public_location_id BIGINT REFERENCES locations(id),
 UNIQUE(assessment_run_id,phenomenon_key,cluster_key),
 UNIQUE(id,assessment_run_id,pattern_episode_id)
);
CREATE INDEX ix_cluster_generation_episode ON observation_clusters(assessment_run_id,pattern_episode_id);
CREATE INDEX ix_cluster_episode_history ON observation_clusters(pattern_episode_id,assessment_run_id);
CREATE INDEX ix_cluster_centroid ON observation_clusters USING gist(centroid_internal);
CREATE INDEX ix_location_public_geometry ON locations USING gist(public_geometry);
CREATE TABLE cluster_members (
 cluster_id BIGINT NOT NULL REFERENCES observation_clusters(id),
 normalized_observation_id BIGINT NOT NULL,
 report_group_id BIGINT NOT NULL,
 membership_id BIGINT NOT NULL,
 representative BOOLEAN NOT NULL,
 PRIMARY KEY(cluster_id,normalized_observation_id),
 FOREIGN KEY(membership_id,normalized_observation_id,report_group_id)
 REFERENCES observation_report_group_members(id,normalized_observation_id,report_group_id)
);
CREATE INDEX ix_cluster_member_observation ON cluster_members(normalized_observation_id);
CREATE UNIQUE INDEX ux_cluster_representative ON cluster_members(cluster_id,report_group_id) WHERE representative;
CREATE TABLE cluster_behavior_summaries (
 cluster_id BIGINT NOT NULL REFERENCES observation_clusters(id),
 behavior_code TEXT NOT NULL CHECK(behavior_code IN ('presence','feeding','fishing','courtship','rut','mating','pupping','aggregation','migration','roosting','sow_with_cubs','lunge_feeding','breaching')),
 observation_count INTEGER NOT NULL CHECK(observation_count>0),
 independent_report_count INTEGER NOT NULL CHECK(independent_report_count>0),
 independent_source_count INTEGER NOT NULL CHECK(independent_source_count>0),
 PRIMARY KEY(cluster_id,behavior_code)
);
CREATE TABLE pattern_generation_runs (
 assessment_run_id BIGINT PRIMARY KEY REFERENCES assessment_runs(id),
 policy_hash TEXT NOT NULL CHECK(length(policy_hash)=64),
 mode TEXT NOT NULL CHECK(mode='shadow'),
 calculated_at TIMESTAMPTZ NOT NULL,
 expected_clusters INTEGER NOT NULL CHECK(expected_clusters>=0),
 expected_episodes INTEGER NOT NULL DEFAULT 0 CHECK(expected_episodes>=0)
);
CREATE TABLE pattern_generation_sources (
 assessment_run_id BIGINT NOT NULL REFERENCES pattern_generation_runs(assessment_run_id),
 source_id BIGINT NOT NULL,
 source_run_id BIGINT NOT NULL,
 content_sha256 TEXT,
 PRIMARY KEY(assessment_run_id,source_id),
 FOREIGN KEY(source_run_id,source_id) REFERENCES source_runs(id,source_id)
);
CREATE TABLE pattern_observation_dispositions (
 assessment_run_id BIGINT NOT NULL REFERENCES pattern_generation_runs(assessment_run_id),
 phenomenon_key TEXT NOT NULL,
 normalized_observation_id BIGINT NOT NULL REFERENCES normalized_observations(id),
 disposition TEXT NOT NULL CHECK(disposition IN ('cluster_input','regional','excluded_precision','excluded_time','excluded_credibility','noise','incoherent','behavior_gate')),
 PRIMARY KEY(assessment_run_id,phenomenon_key,normalized_observation_id)
);
CREATE TABLE pattern_episode_snapshots (
 assessment_run_id BIGINT NOT NULL REFERENCES assessment_runs(id),
 pattern_episode_id BIGINT NOT NULL REFERENCES pattern_episodes(id),
 cluster_id BIGINT,
 status TEXT NOT NULL CHECK(status IN ('developing','qualified','ended')),
 started_at TIMESTAMPTZ NOT NULL,
 last_supported_at TIMESTAMPTZ NOT NULL,
 ended_at TIMESTAMPTZ,
 public_location_id BIGINT REFERENCES locations(id),
 contains_sensitive_evidence BOOLEAN NOT NULL,
 policy_version TEXT NOT NULL,
 policy_hash TEXT NOT NULL CHECK(length(policy_hash)=64),
 parent_episode_id BIGINT REFERENCES pattern_episodes(id),
 merged_into_episode_id BIGINT REFERENCES pattern_episodes(id),
 transition_code TEXT NOT NULL CHECK(transition_code IN ('created','continued','split','merged','expired','policy_changed','unsupported','merge_ambiguous')),
 material_fingerprint TEXT NOT NULL CHECK(length(material_fingerprint)=64),
 PRIMARY KEY(assessment_run_id,pattern_episode_id),
 FOREIGN KEY(cluster_id,assessment_run_id,pattern_episode_id)
 REFERENCES observation_clusters(id,assessment_run_id,pattern_episode_id)
);
CREATE TABLE pattern_episode_revisions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 assessment_run_id BIGINT NOT NULL,
 pattern_episode_id BIGINT NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL,
 FOREIGN KEY(assessment_run_id,pattern_episode_id)
 REFERENCES pattern_episode_snapshots(assessment_run_id,pattern_episode_id),
 UNIQUE(assessment_run_id,pattern_episode_id)
);
CREATE INDEX ix_episode_revisions ON pattern_episode_revisions(pattern_episode_id,assessment_run_id);
ALTER TABLE assessment_opportunities ADD COLUMN pattern_episode_id BIGINT REFERENCES pattern_episodes(id);
